# ==========================================================
# Rosé Pine Color Palette
# ==========================================================
$base         = rgba(25, 23, 36, 1.0)
$surface      = rgba(31, 29, 46, 1.0)
$overlay      = rgba(39, 38, 53, 1.0)
$muted        = rgba(110, 106, 134, 1.0)
$subtle       = rgba(144, 140, 170, 1.0)
$text         = rgba(224, 222, 244, 1.0)
$love         = rgba(235, 111, 146, 1.0)
$gold         = rgba(246, 193, 119, 1.0)
$rose         = rgba(235, 188, 186, 1.0)
$pine         = rgba(49, 116, 143, 1.0)
$foam         = rgba(156, 207, 216, 1.0)
$iris         = rgba(196, 160, 245, 1.0)

# ==========================================================
# General & Background Settings
# ==========================================================
general {
    hide_cursor = false
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    color = $base
}

# ==========================================================
# Container Box Panel
# ==========================================================
shape {
    monitor =
    size = 1632, 918
    color = $base
    rounding = 12
    border_size = 4
    border_color = $surface
    position = 0, 0
    halign = center
    valign = center
}
label {
    monitor =
    text = Oh, look. It's $USER, probably dodging work again ;).
    color = $muted
    font_size = 24
    font_family = ProggyCleanTT
    zindex = 1
    position = 0, -70
    halign = center
    valign = center
}

label {
    monitor =
    text = perseverance<br/>inevitability<br/>accumulation
    color = $muted
    font_size = 16
    font_family = JetBrains Mono
    text_align = left
    position = 165, -95
    halign = left
    valign = top
}

# ==========================================================
# Simple Native 12-Hour Clock
# ==========================================================
label {
    monitor =
    text = cmd[update:1000] date +"%I:%M"
    color = $gold
    font_family = ProggyCleanTT
    font_size = 120
    zindex = 1
    position = 0, 100
    halign = center
    valign = center
}

# ==========================================================
# User Password Input Field
# ==========================================================
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 1
    dots_text_format = *
    dots_size = 0.35
    dots_spacing = 0.25
    dots_center = true
    outer_color = $overlay
    inner_color = $surface
    font_color = $love
    fail_color = $rose
    fail_text = <i>Wrong. That's $ATTEMPTS time you've forgotten your own name.</i>
    fail_transition = 100
    font_family = JetBrains Mono
    rounding = 3
    fade_on_empty = false
    placeholder_text =
    position = 0, 0
    halign = center
    valign = center
}


