set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


base="#191724"
basedawn="#faf4ed"
surface="#1f1d2e"
overlay="#26233a"

muted="#6e6a86"
subtle="#908caa"
text="#e0def4"
aqua="#8ec07c"
love="#eb6f92"
gold="#f6c177"
rose="#ebbcba"
pine="#31748f"
foam="#9ccfd8"
iris="#c4a7e7"

highlightlow="#21202e"
highlightmed="#403d52"
highlighthigh="#524f67"

# set -g status 2

# copy mode
setw -g mode-style "fg=${basedawn},bg=${pine}"

# pane borders
set -g pane-border-style "fg=${muted}"
set -g pane-active-border-style "fg=${foam}"

# statusbar
wg_sep="#[fg=${text}] | "
wg_prfx="#[fg=${gold}]#{?client_prefix,[Prefix],} "
wg_time="#[fg=${text}]%H#[fg=${subtle},bold]:#[fg=${text}]%M"
wg_date="#[fg=${text}]%d#[fg=${subtle}]/#[fg=${text}]%b#[fg=${subtle}]/#[fg=${text}]%Y"
wg_path="#[fg=${iris},bg=${highlightlow},bold]  #(bash -c 'echo #{pane_current_path} | sed \"s|$HOME|~|\"') "

set -g status-style "bg=${highlightlow},fg=${text}"
set -g status-left "#[fg=${rose},bg=${highlightlow},bold][#S] "
set -g status-right "${wg_prfx} ${wg_time}"
set -g status-justify left
set -g status-position top
set -g status-right-length 100
set -g status-left-length 100

# remove default separator space
set -g window-status-separator " "

# Inactive window
set -g window-status-format "#[fg=${text},bg=${highlightlow},bold]#I:#W"

# Active window
set -g window-status-current-format "#[fg=${text},bg=${highlightlow},bold]#I:#W*"

# messages
set -g message-style "bg=#a06666 fg=${base}"

set -g status-format[1] '#[bg=#191724]'

run '~/.tmux/plugins/tpm/tpm'
